# Generated by Django 3.2.7 on 2021-10-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(max_length=10)),
                ('query', models.CharField(max_length=256)),
            ],
        ),
    ]
